Repository WakuWaku-Developer/WakuWaku-BackEnd, pull requests merged in 2024-04, with the labels that each got.

#10 [#9] Build: 프로파일 gitignore 추가
  .gitignore
Labels: ⚙️ Chore

#16 [#11] Feat: 멤버 CRUD 컨트롤러 추가
  src/main/java/dev/backend/WakuWaku/domain/member/controller/member/MemberController.java
Labels: 🟢 Feat, 🌱Init

#34 #30 [Fix] 테스트 커버리지 측정 시 예외 패턴 적용 및 SonarCloud 관련 설정 수정
  build.gradle
  lombok.config
  src/main/java/dev/backend/wakuwaku/domain/BaseEntity.java
  src/main/java/dev/backend/wakuwaku/domain/StatusEntity.java
  src/main/java/dev/backend/wakuwaku/global/config/ApiDocumentConfig.java
  src/main/java/dev/backend/wakuwaku/global/config/CorsConfig.java
  src/main/java/dev/backend/wakuwaku/global/infra/google/places/constant/GooglePlacesAPIRequestConstant.java
  src/main/java/dev/backend/wakuwaku/global/infra/google/places/dto/request/TextSearchRequest.java
  src/test/java/dev/backend/wakuwaku/domain/member/repository/MemberRepositoryTest.java
  src/test/resources/application.yml
Labels: 🟢 Feat, ♻️ Refactor
