Repository WakuWaku-Developer/WakuWaku-BackEnd, pull requests merged in 2024-09, with the labels that each got.

#84 [#82] Feat: 회원 찜 기능 구현
  src/main/java/dev/backend/wakuwaku/domain/likes/controller/LikesController.java
  src/main/java/dev/backend/wakuwaku/domain/likes/dto/LikesStatusType.java
  src/main/java/dev/backend/wakuwaku/domain/likes/dto/request/LikesRequest.java
  src/main/java/dev/backend/wakuwaku/domain/likes/dto/response/LikesResponse.java
  src/main/java/dev/backend/wakuwaku/domain/likes/entity/Likes.java
  src/main/java/dev/backend/wakuwaku/domain/likes/repository/LikesRepository.java
  src/main/java/dev/backend/wakuwaku/domain/likes/service/LikesService.java
  src/main/java/dev/backend/wakuwaku/domain/member/entity/Member.java
  src/main/java/dev/backend/wakuwaku/global/exception/ExceptionStatus.java
  src/main/java/dev/backend/wakuwaku/global/exception/WakuWakuException.java
  src/test/java/dev/backend/wakuwaku/domain/like/controller/LikesControllerTest.java
  src/test/java/dev/backend/wakuwaku/domain/like/repository/LikesRepositoryTest.java
  src/test/java/dev/backend/wakuwaku/domain/like/service/LikesServiceTest.java
  src/test/java/dev/backend/wakuwaku/domain/member/controller/MemberControllerTest.java
  src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
  src/test/java/dev/backend/wakuwaku/domain/oauth/service/OauthServiceTest.java
Labels: 🟢 Feat, 🌱Init

#88 [#83] Feat: 모니터링 시스템 도입
  build.gradle
  src/main/java/dev/backend/wakuwaku/domain/likes/service/LikesService.java
  src/main/java/dev/backend/wakuwaku/global/infra/google/places/details/GooglePlacesDetailsService.java
  src/main/java/dev/backend/wakuwaku/global/infra/google/places/photo/GooglePlacesPhotoService.java
  src/main/java/dev/backend/wakuwaku/global/infra/google/places/textsearch/GooglePlacesTextSearchService.java
  src/main/java/dev/backend/wakuwaku/global/infra/redis/service/RedisService.java
  src/main/java/dev/backend/wakuwaku/global/util/config/MonitoringConfig.java
  src/test/java/dev/backend/wakuwaku/global/infra/redis/service/RedisServiceTest.java
Labels: 🟢 Feat, ⚙️ Chore

#90 [#89] HOTFIX: Docker 계정 변경으로 인한 Docker Compose 이미지 이름 변경
  docker-compose.yml
Labels: 🧨 HOTFIX

#92 [#91] Fix: API 문서 접속 URL 수정
  build.gradle
Labels: 🛠️ Fix

#94 [#93] Fix: API 서버 메트릭을 가져오지 못하는 이슈
  docker-compose.yml
Labels: 🛠️ Fix, 📝 Docs

#99 [#98] Fix: 구매한 도메인 CORS 추가
  src/main/java/dev/backend/wakuwaku/global/config/CorsConfig.java
Labels: 🛠️ Fix

#100 [#96] Fix: 로그인 응답 데이터 수정
  src/main/java/dev/backend/wakuwaku/domain/oauth/controller/OauthController.java
  src/main/java/dev/backend/wakuwaku/domain/oauth/dto/response/OAuthLoginResponse.java
  src/main/java/dev/backend/wakuwaku/global/config/CorsConfig.java
  src/test/java/dev/backend/wakuwaku/domain/oauth/controller/OauthControllerTest.java
Labels: 🛠️ Fix

#101 [#97] Refactor: 구글 계정으로 로그인 시, 사용자 닉네임을 제대로 가져오도록 구현
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/google/GoogleMemberClient.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/google/dto/GoogleMemberResponse.java
  src/test/java/dev/backend/wakuwaku/global/infra/oauth/client/OauthMemberClientCompositeTest.java
  src/test/java/dev/backend/wakuwaku/global/infra/oauth/google/GoogleMemberClientTest.java
Labels: ♻️ Refactor

#104 [#103] Fix: 카카오 소셜 로그인 안 됨
  docker-compose.yml
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/kakao/client/KakaoApiClient.java
Labels: 🛠️ Fix

#106 [#105] Fix: 카카오 소셜 로그인 시 사용자 정보 요청 때 헤더에 content type 추가
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/kakao/KakaoMemberClient.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/kakao/client/KakaoApiClient.java
  src/test/java/dev/backend/wakuwaku/global/infra/oauth/kakao/KakaoMemberClientTest.java
Labels: 🛠️ Fix

#108 [#107] HOTFIX: Kakao 소셜 로그인 에러
  src/main/java/dev/backend/wakuwaku/domain/oauth/controller/OauthController.java
  src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/client/OauthMemberClientComposite.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/kakao/KakaoMemberClient.java
Labels: 🧨 HOTFIX

#109 [#107] Hotfix: 카카오 소셜 로그인 오류 수정
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/google/client/GoogleApiClient.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/kakao/KakaoMemberClient.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/kakao/KakaoOauthConfig.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/kakao/client/KakaoApiClient.java
  src/main/java/dev/backend/wakuwaku/global/infra/oauth/naver/NaverOauthConfig.java
Labels: 🧨 HOTFIX

#110 [#102] Fix: 찜 목록 조회 시 각 찜 객체의 id 값도 포함하여 응답하도록 수정
  docker-compose.yml
  src/main/java/dev/backend/wakuwaku/domain/likes/dto/response/AllLikesResponse.java
  src/main/java/dev/backend/wakuwaku/domain/likes/dto/response/GetLikesResponse.java
  src/main/java/dev/backend/wakuwaku/domain/likes/dto/response/GetRestaurantResponse.java
  src/main/java/dev/backend/wakuwaku/domain/likes/repository/LikesRepository.java
  src/main/java/dev/backend/wakuwaku/domain/likes/service/LikesService.java
  src/main/resources/application.yml
  src/test/java/dev/backend/wakuwaku/domain/like/controller/LikesControllerTest.java
  src/test/java/dev/backend/wakuwaku/domain/like/service/LikesServiceTest.java
Labels: 🛠️ Fix
